### ISSUE TITLE
Feature Additions.

### ISSUE THREAD

**Issue by MaNaReaver** [AoiKagase/Amxx-MusicMenuAdvance#1]
Hey Aoi, I and a lot of players on our server love your Music Menu Plugin! However, it would be great if you could consider adding a few more options and features for the plugin.

1. Have a Play All option in the menu that shuffles (plays random) music from the playlist.
2. Have a Background Music cvar (that can be turned on/off), and plays all the tracks from the playlist (basically the 1st feature) as soon as a player joins the server.

Thanks for considering these features, and great work again!
Best regards,
MaNa.

**Comment by AoiKagase** [comment]
To create a playlist feature, you need to add the play time of each song to the INI file yourself.
Can you do it?

**Comment by MaNaReaver** [comment]
Yeah, that wouldn't be an issue. Thanks for the speedy reply :D

**Comment by MaNaReaver** [comment]
Hey Aoi, I compiled the plugin with AMX 1.9.0 5270 and tested the plugin without any other plugins running, but unfortunately, it's giving me a Segmentation Fault (core dumped) error. The older versions (3.02 and 3.03a) are working fine, so I'm guessing something's going wrong. Can you also edit the bgmlist.ini with the updated format too? I don't think that bgmlist.ini has any issues though, as I tried different combinations, and the crash still persisted. 

My current bgmlist format is:
Song1; Directory1; 04:00

**Comment by AoiKagase** [comment]
From this time on, I'm using nvault to record player setting data.
Maybe there is an error there.

additional features: 
- /mma config
- Playback of the playlist (shuffle, in order)
- Volume control

**Comment by MaNaReaver** [comment]
Hey Aoi, the plugin is functioning perfectly now! Amazing work <3 

There were just a few modifications that required some more work:
1. The 1st page of the music menu is missing 3, causing the menu to show 0 instead of 9 for More, and 11 instead of 0 for Exit. The rest of the pages are fine, I guess it's because the Playlist option took the 1st place.
2. There can be a Sync HUD added to show the timeframe of the music, which would complement the plugin.
3. I had a look through the plugin, but couldn't find a forward option, can you have a look at it?

Thanks again for doing a great job on the plugin!

**Comment by AoiKagase** [comment]
forward = in order option.
I made a mistake.
