### ISSUE TITLE
Menu is missing.

### ISSUE THREAD

**Issue by AoiKagase** [AoiKagase/Amxx-MusicMenuAdvance#2]
Hey Aoi, the plugin is functioning perfectly now! Amazing work <3 

There were just a few modifications that required some more work:
1. The 1st page of the music menu is missing 3, causing the menu to show 0 instead of 9 for More, and 11 instead of 0 for Exit. The rest of the pages are fine, I guess it's because the Playlist option took the 1st place.
2. There can be a Sync HUD added to show the timeframe of the music, which would complement the plugin.
3. I had a look through the plugin, but couldn't find a forward option, can you have a look at it?

Thanks again for doing a great job on the plugin!

_Originally posted by @MaNaReaver in https://github.com/AoiKagase/Amxx-MusicMenuAdvance/issues/1#issuecomment-640184343_

**Comment by MaNaReaver** [comment]
For some more clarification, the menu shows up, but the issue's with the numbers that take up the slots on the 1st page of the menu, which shows as follows:

1 Play All.
2 STOP BGM.

4 Song1
5 Song2
6 Song3
7 Song4
8 Song5

9 Back
0 More
11 Exit

The next pages are fine with 1-7 occupied by songs, and 8,9 and 0 occupied by Back, More and Exit.

**Comment by AoiKagase** [comment]
@MaNaReaver This issue is Fixed.
