### ISSUE TITLE
Sync HUD added to show the timeframe

### ISSUE THREAD

**Issue by AoiKagase** [AoiKagase/Amxx-MusicMenuAdvance#3]
Hey Aoi, the plugin is functioning perfectly now! Amazing work <3 

There were just a few modifications that required some more work:
1. The 1st page of the music menu is missing 3, causing the menu to show 0 instead of 9 for More, and 11 instead of 0 for Exit. The rest of the pages are fine, I guess it's because the Playlist option took the 1st place.
2. There can be a Sync HUD added to show the timeframe of the music, which would complement the plugin.
3. I had a look through the plugin, but couldn't find a forward option, can you have a look at it?

Thanks again for doing a great job on the plugin!

_Originally posted by @MaNaReaver in https://github.com/AoiKagase/Amxx-MusicMenuAdvance/issues/1#issuecomment-640184343_

**Comment by AoiKagase** [comment]
@MaNaReaver Added.

**Comment by MaNaReaver** [comment]
I was able to test the plugin, and it seems that the chat isn't visible anymore after the HUD implementation. Also, the playlist doesn't loop, I guess it's because of the loop variable turned off for everyone.

**Comment by AoiKagase** [comment]
Remove "addons\amxmodx\data\vault\mma.vault", and Test again.
