### ISSUE TITLE
Options to control the music menu

### ISSUE THREAD

**Issue by MaNaReaver** [AoiKagase/Amxx-MusicMenuAdvance#4]
Hey Aoi, 

I received a few suggestions from players, who told me they'd love to see say commands like /forward, /back, and /stop to move to next track, previous track, and stop music altogether. I think it would help give more control to players and would be a good addition to the player overall. What do you think?

PS: Regarding the previous issue, the plugin worked great after resetting the vault which had the settings previously loaded. 

Best regards,
MaNa.

**Comment by AoiKagase** [comment]
Adding easy commands may interfere with other plugins.
So, I think it should be a special command like "/mma forward" if you add it. 
```
/mma next
/mma back
/mma stop
```

**Comment by MaNaReaver** [comment]
Yeah, but I guess it wouldn't be a hassle to change the command if it clashes or interferes with other plugins.

**Comment by MaNaReaver** [comment]
Thanks, these commands work great! However, I checked back on the vault, and the values return back to the default ones when you reconnect. I don't know why that's happening despite the values being saved and then loaded on join from get_cl_cvar. Can you check and let me know if it's the case? If it's not happening to you, I guess there's an issue with my vault.

Also, when anyone selects a song from the list, it plays a different song, showing two messages:
[MMA] BGM Start!:[Song1] ;Song1 was selected from the menu
[MMA] Playing:01:[Songn] ;Songn plays instead from the random shuffle list [the song is 1st in that list]

Best regards.

**Comment by AoiKagase** [comment]
If you encounter another issue, please post another Issue.
I'll close this one for now.
